import sqlite3

# Connect to the database (creates it if it doesn't exist)
conn = sqlite3.connect('data.db')
c = conn.cursor()

# 1. Create the users table
# NOTE: The 'password' column stores the secure hash generated by werkzeug.
c.execute('''
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY,
        username TEXT NOT NULL UNIQUE,
        password TEXT NOT NULL
    )
''')

# 2. Create the players table (for Modo Carrera)
c.execute('''
    CREATE TABLE IF NOT EXISTS players (
        id INTEGER PRIMARY KEY,
        user_id INTEGER NOT NULL,
        position TEXT NOT NULL,
        name TEXT NOT NULL,
        age INTEGER,
        nationality TEXT,
        grl INTEGER,
        market_value TEXT,
        salary TEXT,
        FOREIGN KEY (user_id) REFERENCES users (id)
    )
''')

# Save (commit) the changes and close the connection
conn.commit()
conn.close()

print("Database 'data.db' created and tables initialized.")
